### ISSUE TITLE
CondaVerificationError w/ Conda 4.3

### ISSUE THREAD

**Issue by alanhdu** [conda-forge/sympy-feedstock#4]
Under Conda 4.3.1, installing `sympy` from `conda-forge` leads to a bunch of shared path errors:

```
CondaVerificationError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::gmpy2-2.0.7-py35_1, conda-forge::mpmath-0.19-py35_1
  path: lib/python3.5/distutils/command/__pycache__/install_egg_info.cpython-35.pyc
If you'd like to proceed anyway, re-run the command with the `--force` flag.
```

and 

```
CondaVerificationError: The package 'conda-forge::mpmath-0.19-py35_1' cannot be installed due to a
path collision for 'lib/python3.5/distutils/command/__pycache__/build.cpython-35.pyc'.
This path already exists in the target prefix, and it won't be removed by
an uninstall action in this transaction. The path appears to be coming from
the package 'conda-forge::setuptools-32.3.0-py35_0', which is already installed in the prefix. If you'd like
to proceed anyway, re-run the command with the `--force` flag.
```

You can reproduce this with the following `Dockerfile`:

```Dockerfile
FROM continuumio/miniconda3

RUN conda config --add channels conda-forge
RUN conda config --add channels conda-canary

RUN conda update --yes --all

RUN conda install --yes sympy
```

**Comment by alanhdu** [comment]
Reading the release notes, this seems like an intentional breaking change in conda:

> Conda will refuse to clobber existing files that are not within the unlink instructions of the transaction. At the risk of being user-hostile, it's a step forward for conda. We do anticipate some growing pains. For example, conda will not clobber packages that have been installed with pip (or any other package manager). In other instances, conda packages that contain overlapping file paths but are from different package families will not install at the same time. The --force command line flag is the escape hatch. Using --force will let your operation proceed, but also makes clear that you want conda to do something it considers unsafe.

I've also run into this in a couple of other `conda-forge` packages, so this might be a broader problem than just `sympy`. Let me know if this should be filed somewhere else!

**Comment by asmeurer** [comment]
The common path looks like some setuptools junk. Maybe (hopefully) the latest conda-build cleans that up. I wonder if a rebuild would fix this. CC @msarahan

**Comment by ElimsV** [comment]
Hi I have encountered a similar problem when I want to clone an existing conda env. It gives a lot of verification transaction errors like this:

SafetyError: The package for scipy located at /home/ursname/.conda/pkgs/scipy-1.0.1-py36hfc37229_0
appears to be corrupted. The path 'lib/python3.6/site-packages/scipy/special/tests/__pycache__/test_sici.cpython-36.pyc'
has a sha256 mismatch.
  reported sha256: 99cc92477c68514f2177e4e74bc4b38d5814bd4a9419a9b3a1e46ff93adaf097
  actual sha256: fe98dccfa65f205437b3113d497fce0a7f5aa4917945605524d357f78dfaa9d7

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults::tensorboard-1.7.0-py36hf484d3e_0, defaults::tensorflow-tensorboard-1.5.1-py36hf484d3e_0
  path: 'lib/python3.6/site-packages/tensorboard/plugins/custom_scalar/__init__.py'

 The original env just works fine. Do you have idea why? Thanks in advance!

**Comment by liuajian** [comment]
@ElimsV 
Can you resolve this problem? Thanks

**Comment by ocefpaf** [comment]
Indeed this is a not a sympy issue. Not sure where is the "right" place to fix it.

cc. @msarahan and @kalefranz

**Comment by ElimsV** [comment]
@liuajian 
I solved by running:
conda clean -a
and then re-clone the env. It works for me. I would guess some package caches are some how messed up.
